### PR TITLE
Fix a problem with CLI -b argument misbehaving

### LINKED ISSUE #222: cli -b and --bowerJson produce different results
If running via this CLI, **-b filename** does not behave properly, as the scripts reads the JSON contents of the *filename*, puts it in the same **-b** property and later overwrites it again with just the *filename*.
This only happens for **-b**, not for **--bowerJson**.

PR to follow soon.

### PR DESCRIPTION
**Pull request by danielsiwiec**
Also adding a couple simple tests for the CLI. Closes #222

### CODE REVIEW

File: wiredep-cli.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ if (!argv.s && !argv.src) {
 
 if (argv.b || argv.bowerJson) {
   try {
-    argv.bowerJson = JSON.parse(fs.readFileSync(argv.b || argv.bowerJson));
+    argv.b = JSON.parse(fs.readFileSync(argv.b || argv.bowerJson));
```
Comment (stephenplusplus) [inline wiredep-cli.js]: I think all we need here is:

```diff
if (argv.b || argv.bowerJson) {
  try {
      argv.bowerJson = JSON.parse(fs.readFileSync(argv.b || argv.bowerJson));
+     delete argv.b;
  } catch (e) {}
}
```

The problem is later in the script with this code:

```js
if (argObj.short === arg) {
  acc[argObj.full] = argv[arg];
  delete acc[arg];
}
```

This block is responsible for taking all of the shorthand input and renaming it to what the wiredep API expects.

Earlier, when `.b` was transformed into `.bowerJson`, we didn't remove `.b`. That tricked this code into thinking there is only a `.b` and it needs to be renamed to its full name, `.bowerJson`. So, basically, it just overwrites what we did earlier.

Sorry for the iffy code :(

Comment (danielsiwiec) [inline wiredep-cli.js]: Yup, that works too. Let me update the PR

**Comment by stephenplusplus** [comment]
Thanks very much. Released as 3.0.0.
